'use strict';

const keyTokenModel = require('../models/keyToken.model');

class KeyTokenService {
    static createKeyToken = async ({ userId, publicKey }) => {
        try {
            // publicKey is generated by an asymmetric algorithm so it is a buffer, need to convert to string
            const publicKeyString = publicKey.toString();

            const tokens = await keyTokenModel.create({
                user: userId,
                publicKey: publicKeyString,
            });

            return tokens ? tokens.publicKey : null;
        } catch (error) {
            return error;
        }
    };
}

module.exports = KeyTokenService;
