@urlDev=http://localhost:3000/v1/api/

### Login
POST {{urlDev}}auth/shop/login
Content-Type: application/json
x-api-key: helloworld

{
    "email": "test1@gmail.com",
    "password": "abc123"
}

### signUp
POST {{urlDev}}auth/shop/sign-up
Content-Type: application/json
x-api-key: helloWorld

{
    "name": "Demo",
    "email": "test1@gmail.com",
    "password": "abc123"
}

### Logout
POST {{urlDev}}auth/shop/logout
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
authorization: accessToken

### Handle refresh token
POST {{urlDev}}auth/shop/handle-refresh-token
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
x-rtoken-id: refreshToken
