@urlDev=http://localhost:3000/v1/api/

### Create a product
POST {{urlDev}}products
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
authorization: accessToken

{
    "productName": "iPhone 15 Pro 123GB",
    "productThumb": "productThumb",
    "productDescription": "6.1-inch Super Retina XDR display footnote, featuring ProMotion, Always-On, and Dynamic Island",
    "productPrice": 1199,
    "productQuantity": 100,
    "productType": "Furniture",
    "productAttributes": {
        "brand": "Apple",
        "size": "Pro",
        "material": "Steel"
    },
    "productVariations": ["Normal", "Plus", "Pro", "Pro Max"]
}

### Update a product
PATCH  {{urlDev}}products/:id
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
authorization: accessToken

{
    "productName": "iPhone 15 Pro 123GB",
    "productThumb": "productThumb",
    "productDescription": "6.1-inch Super Retina XDR display footnote, featuring ProMotion, Always-On, and Dynamic Island",
    "productPrice": 1199,
    "productQuantity": 100,
    "productType": "Furniture",
    "productAttributes": {
        "brand": "Apple",
        "size": "Pro",
        "material": "Steel"
    },
    "productVariations": ["Normal", "Plus", "Pro", "Pro Max"]
}

### Publish a product
PATCH {{urlDev}}products/:id/publish
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
authorization: accessToken

### Un Publish a product
PATCH {{urlDev}}products/:id/un-publish
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
authorization: accessToken

### Get all draft products
GET {{urlDev}}products/drafts
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
authorization: accessToken

### Get all draft products
GET {{urlDev}}products/published
Content-Type: application/json
x-api-key: helloworld
x-client-id: 1
authorization: accessToken

### Search products by keyword
GET {{urlDev}}products/search/:keyword
Content-Type: application/json
x-api-key: helloworld

### Get all products
GET {{urlDev}}products
Content-Type: application/json
x-api-key: helloworld

### Find a product by id
GET {{urlDev}}products/:id
Content-Type: application/json
x-api-key: helloworld
